remote_theme: fongandrew/hydeout

url: ""
baseurl: ""

title:            Guillem Lefait
description:      Data Butcher. CDO @<a href="https://tvty.tv/">TVTY</a>, @<a href="https://datamq.com/">DataMQ</a>

author:
  name:           Guillem Lefait
  url:            https://guillem.lefait.fr/
  email:          guillem@hey.com
  twitter_username: guillem_lefait
  github_username:  glefait
  linkedin_username:  glefait
  stackoverflow_url:  https://stackoverflow.com/users/3090365/glefait

paginate:   5
comments:           false
sidebar_home_link:  true
show_drafts: false

include:
 - .well-known
